package com.friendly_machines.fr_yhe_api.watchprotocol

enum class WatchResponseType {
    SetMessage,
    ChangeAlarm,
    SetStepGoal,
    Unbind,
    Bind,
    SetProfile,
    SetDndSettings,
    GetAlarms,
    SetWatchWearingArm,
    SetWatchTimeLayout,
    GetWatchDials,
    ChangeWatchDial,
    SetSkinColor,
    SetWatchScheduleEnabled,
    GetFileList,
    SetWeather,
    SetRegularReminder,
    SetHeartMonitoring,
    SetHeartAlarm,
    SetUnits,
    SetLanguage,
    SetRaiseToWake,
    SetDisplayBrightness,
    SetAntiLoss,
    SetEventReminderMode,
    SetTemperatureAlarm,
    SetAccidentMonitoringEnabled,
    SetTemperatureMonitoring,
    SetSportMode,
}