name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (v1.0.0, etc)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    # If you want to use signing keys stored in GitHub Secrets, uncomment these steps
    # - name: Decode Keystore
    #   run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks
    #   
    # - name: Build signed release APK
    #   run: >-
    #     ./gradlew assembleRelease 
    #     -Pandroid.injected.signing.store.file=keystore.jks 
    #     -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} 
    #     -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} 
    #     -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
      
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true